sudo: false
language: node_js
node_js:
  - '6'
  - '4'
cache:
  directories:
    - node_modules
notifications:
  email: false
before_script:
  - npm prune
after_success:
  - npm run coveralls
  - npm run release
