build: off
environment:
  matrix:
    - nodejs_version: '5'
    - nodejs_version: '4'
    - nodejs_version: '0.12'
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
test_script:
  - npm test
